### ISSUE TITLE
Auth not working well

### ISSUE THREAD

**Issue by yuxxeun** [justdlabs/inertia.ts#99]
I tried creating a new project with this boilerplate, but when I tried to logout, I got this error message:

![image](https://github.com/user-attachments/assets/baafd9dc-a5fd-43bf-b1ed-6c3bbf39a601)

And then when I'm trying to login with my account (fyi, I've registering new account), with route `base_url/login` not with `/dev/login/id` route, i got nothing, still on the login page:

![image](https://github.com/user-attachments/assets/abec02a1-c2f8-47af-9eb7-77a485048cdf)

**Comment by irsyadadl** [comment]
Make sure to run npm run dev. After that, make sure the APP_URL is match with your current setup.

**Comment by yuxxeun** [comment]
yup, everything's is running

![image](https://github.com/user-attachments/assets/01cb390b-40e9-4356-9008-4ef1cf2e6899)

**Comment by irsyadadl** [comment]
Just make sure you are on the right path url. If your application is called inertia.ts, and make it inertia.ts.test, if you're using `artisan serve`, replace it with `127....`. And after that make sure you run the `npm run dev`. Because the route will generated when you run dev. See on the `vite.config.js`

```js
watch({
    pattern: 'routes/web.php',
    command: 'php artisan ziggy:generate'
})
```
